### ISSUE TITLE
travis codecov

### ISSUE THREAD

**Issue by ripoul** [ripoul/url-shortener-api#21]
use matrix to execute only one time codecove (2 python version = 2 scripts excuted)

**Comment by ripoul** [comment]
```yml
matrix:
  include:
    - name: "Python 2.7.14 on macOS 10.13"
      os: osx
      osx_image: xcode9.3  # Python 2.7.14_2 running on macOS 10.13
      language: shell  # 'language: python' errors on Travis CI macOS
      before_install:
        - python --version
        - pip install pytest --user
        - pip install codecov --user
      install: pip install ".[test]" --user
      script: python -m pytest  # pytest command won't be found
      after_success: python  -m codecov  # codecov command won't be found
```
